version: "2"

services:
  site:
    build:
      context: .
    ports:
      - 8092:80
    networks:
      - traefik
    labels:
      - traefik.http.routers.portfolio.rule=Host(`portfolio.vaskovasilev.eu`) || Host(`vaskovasilev.eu`)
    restart: always

  puller:
    image: tuxity/docker-image-puller
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik:
    external:
      name: downloads_traefik #That's just my already existing traefik network
