version: "2"

services:
  site:
    build:
      context: .
    image: sp0x/portfolio
    ports:
      - 8092:80
    networks:
      - traefik
    labels:
      - traefik.http.routers.portfolio.rule=Host(`portfolio.vaskovasilev.eu`) || Host(`vaskovasilev.eu`)
    restart: always

networks:
  traefik:
    external:
      name: downloads_traefik #That's just my already existing traefik network
